### ISSUE TITLE
proposal: remove void element map in core and move responsibility to element function

### ISSUE THREAD

**Issue by SirMetathyst** [maragudk/gomponents#124]
Element functions are part of a separate package but the core has knowledge over tags and what tag is a void element which is strange to me. How about creating a new function `VoidEl` or adding an extra param to existing function before children?  This way the element function itself can decide if it is a void element or not.

**Comment by markuswustenberg** [comment]
Since the core package is all about writing HTML5, I think it's fine to have void element knowledge there. Everything in package `html` is just helpers. You could use just the `gomponents` package to write your HTML and be fine. Having a `VoidEl` would move the burden of deciding which HTML5 elements are void elements to the API user, and I'd rather have the library decide that for them.

(Thanks for all the feedback, even if I don't agree. 😊)

**Comment by SirMetathyst** [comment]
I understand your reasoning and acknowledge your point about the burdening the user with deciding which HTML5 elements are void elements. Furthermore there are not many void elements anyway and the project is a html5 rendering package.
