### ISSUE TITLE
trigger an error on duplicate attributes

### ISSUE THREAD

**Issue by vikstrous2** [maragudk/gomponents#161]
I spent a while trying to track down a bug I had which was caused by the fact that I defined the same attribute twice. The second instance was ignored by the browser. It would be better if Gomponents would error early when this happens rather than let the browser misinterpret my intent.

**Comment by markuswustenberg** [comment]
Hi @vikstrous2 . Thank you for your issue! I understand that it can be frustrating that the library lets you do this.

However, I've intentionally not ventured into the can of worms that is "validating whether the output is correct HTML", since that is a huge, complex issue. I'll leave that up to the browser. In that regard, writing components with gomponents is just like writing HTML.

I would recommend you add separate tooling in e.g. your unit tests to check for stuff like this, I'm sure something exists.

I hope you figure out a solution suitable to your needs! 😊

**Comment by vikstrous2** [comment]
Yeah, I see what you mean. I found a few resources for validating html. None in Go, but that's fine for now. Feel free to close this.

**Comment by markuswustenberg** [comment]
Good to hear!
