### ISSUE TITLE
Figure out what can be done about name collisions between elements and attributes

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#170]
Might be nice to have a non-breaking strategy going forward, if new nodes are added to the HTML spec.

Ideas:
- Select the most used one as the "main" one, and suffix the other. E.g. `TitleEl` and `Title`
- Keep the current scheme, where all collisions have a suffix: `TitleEl` and `TitleAttr` (would mean a breaking change on each new one)

**Comment by Hendrikto** [comment]
I prefer the first option, because:

* It is easy to make backwards-compatible.

  We can just deprecate `TitleXXX` (either `TitleEl` or `TitleAttr`, depending on which one is chosen as the "main" one), but keep it around, and point to `Title` and `TitleYYY` (the other one) in the documentation. Thus, nothing would break, and no translation is needed. Old code can keep using `TitleXXX`, new code can use `Title`.
* It is forwards-compatible, as you pointed out.
* It looks nicer, and is more consistent with all of the other nodes. There is just less noise.

I just think it is important to be consistent. `Title` should always be the same thing, either `TitleAttr` or `TitleEl`. It should not alternate between different titles (`XXX` = `XXXEl` and `YYY` = `YYYEl` NOT `XXX` = `XXXEl` and `YYY` = `YYYAttr`). I assume that is what you meant by

> Select the most used one as the "main" one

but I just wanted to clarify this.

**Comment by markuswustenberg** [comment]
@Hendrikto those are great points! Good idea about the deprecation, I hadn't thought about that we don't actually need to do a breaking change. 

I would prefer:
- TitleEl and Title
- Form and FormAttr
- DataEl and Data

Not sure about Style. Both options kinda suck. 😄

**Comment by markuswustenberg** [comment]
Maybe a slight preference towards StyleEl and Style, because the latter is arguably used more often.

**Comment by markuswustenberg** [comment]
See #174 for the chosen solution for this.
