### ISSUE TITLE
Remove SVG helpers?

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#206]
See comment at https://github.com/maragudk/gomponents/pull/196#issuecomment-2363091120

**Comment by Nintron27** [comment]
I just ran into this project, and can't wait to dig into it more, so, take my comment with a grain of salt. 

I use SVGs a ton, and personally I never render them out element by element in other templating languages I've used. I usually create them in some sort of design tool like Figma, and do one of two things:

1. Add the internal structure of the svg (everything inside the <svg> tag) to something like an assets folder, then just render the SVG tag with it's attributes, and inject the internal structure of the SVG as a raw string. (in Gomponents case this may look something like the pseudocode `g.El("svg", g.Attr(...)..., g.Raw({string from file}))`)
2. Just paste the entire SVG into an assets folder, and create a little tool to inject classes into the class attribute leaving everything else untouched. (I will probably take this option when using gomponents).

So, for my 2 cents, I personally won't use the SVG helpers Gomponents provides but rather use g.El and g.Raw to create my own helper that just renders SVGs from an assets files, and optionally injects classes on it. This solution has covered 100% of my teams needs for using SVGs, and the only case I can think of it not covering, is dynamically changing the internal structure of an SVG, which is an extremely uncommon use case from my experience.

**Comment by markuswustenberg** [comment]
@Nintron27, thank you for your input!

I've come to more or less the same realization: A lot of the benefits of gomponents are basically lost with the SVG parts, as I do the same as you: find an SVG somewhere or create one, then paste it into `Raw` and call it a day.

I only realized this when a kind developer opened #196, and I didn't want to merge it for some reason I wasn't entirely consciously aware of. I think you've explained why better than I could, so thank you for that.

With option two, would you like having an `SVG` helper element with the XML namespace etc. on it and inject only the inner parts, or does it not really matter?

**Comment by Nintron27** [comment]
> With option two, would you like having an `SVG` helper element with the XML namespace etc. on it and inject only the inner parts, or does it not really matter?

For me it probably doesn't matter, since I tend to just paste the entire SVG into an assets folder, add an empty class attribute to it, and then have a helper to inject classes into that class attribute. I may even just use Go's `html/template ParseFiles()` just for this one use to inject classes easier.

**Comment by markuswustenberg** [comment]
Makes sense. Thanks for the answer!

**Comment by Hendrikto** [comment]
I wasn't sure whether to open a new issue or comment on this one. Let me know if you want to discuss somewhere else.

I ran into the same problem of wanting to programmatically create SVGs. Contrary to the use case of embedding static SVGs discussed above, I want to create charts, so they are dynamic and have to be constructed on-the-fly. I just wanted to note that the workflow described above does not work for all use cases.

Of course I can implement my own `Node`s, or I can just the string concatenation. However, since SVG is a common standard, which can even be embedded in HTML and become part of the DOM, I think there would be value in a generalized solution.

**Comment by markuswustenberg** [comment]
@Hendrikto maybe it would make sense to make an gomponents-svg module to try it out? I'm hesitant to add it to core gomponents again, mostly because I don't know much about SVG and the implications of adding it. Trying it out somewhere else first (or maybe under the `x` package like `slices`) would perhaps be a good approach.

Thoughts?
