### ISSUE TITLE
Gomponents vs Templ article : fairness check

### ISSUE THREAD

**Issue by EwenQuim** [maragudk/gomponents#218]
Hi Markus, 

I'm writing an article about Go templating, about **Gomponents vs Templ** and I wanted to make sure I have a state-of-the-art article about your library.

Is it possible to read it and tell me if I get your library wrong somewhere? Of course, I've sent the article to Templ team for proofreading too.

https://nuage.quimerch.com/articles/improving-go-templating-templ-vs-gomponents

Thanks again for your lib ❤️

**Comment by markuswustenberg** [comment]
Hi @EwenQuim,

nice that you're writing that! And thank you for asking for feedback.

I think it's a nice article with good points. Especially agree on the tooling situation. It's not something I've focused on, but I'd love to be able to have my IDE suggest gomponents in the same way as HTML. See #209 for that.

I have a few minor points:
- `Span(g.Text(fmt.Sprintf("%d", props.age)),)`: you can just use `g.Textf` here
- `Minus one to both libs because when you pass a struct, you can always forget to add a field (an unfortunate Go feature).` True, but you could also use a function with regular args instead of passing a struct then. But I get your point.
- I'm starting to use dot imports for All The Things, so it reads just `Node` instead of `g.Node`. You may or may not want to do the same thing.

Regarding the ask at the end: I've just opened #219 for this.

Thanks again, you're awesome! 😎
