### ISSUE TITLE
CSS Modules in gomponents

### ISSUE THREAD

**Issue by philippta** [maragudk/gomponents#83]
Hey @markuswustenberg!

I was just tinkering around with your library again and thought it would be awsome to have something similar to [CSS Modules](https://github.com/css-modules/css-modules) in gomponents. This would be very benefitial for encapsulation and the pain of writing CSS selectors by hand, other options like Tailwind CSS integrate well but can get out of hand pretty quickly. 

I created a proof of concept which integrates nicely with your library and I think it would be an awesome addition.
Attached is a screenshot which should demonstrate the look and feel, not necessarily the implementation details.

Please let me know what you think, especially if you could see this being added to gomponents or if it should rather live in its own package.

Cheers ✌🏼

<img width="1221" alt="cssmodules" src="https://user-images.githubusercontent.com/13717118/122475099-721d6200-cfc4-11eb-8d7e-5bbeddecf4c8.png">

**Comment by markuswustenberg** [comment]
Hey @philippta,

that's awesome! 😎 I think it's a good idea to have this. I'm personally a big fan of TailwindCSS and hadn't heard of CSS modules before now, but I can see how they solve the same problem (styling components) quite elegantly, in different ways.

My initial thought is that this would be nice to have in a separate Go module. I've done something similar with [gomponents-heroicons](https://github.com/maragudk/gomponents-heroicons) and started (but never got far with) [gomponents-tailwind](https://github.com/maragudk/gomponents-tailwind), so a _gomponents-css-modules_ or something would make great sense.

My dream with gomponents is to be part of creating a rich ecosystem of view libraries for Go. I always found that cool about using React in Javascript-land, because there's so many great libraries to choose from. I started a [gomponents +](https://www.gomponents.com/plus/) page on the website to facilitate this, and if you end up creating this, I would love to put the project on there.

What do you think?

**Comment by markuswustenberg** [comment]
@philippta did you ever get further with this?

**Comment by lobre** [comment]
I know this issue is closed and I am two years late on that, but I do think the concept is interesting. That would be a nice extension to gomponents if someone feels like wanting to tackle this topic!
