### ISSUE TITLE
Add constants for common attribute values

### ISSUE THREAD

**Issue by averageflow** [maragudk/gomponents#87]
In order to write cleaner code when working with gomponents, a suggestion I have is that we create some exported constants that can be used for everyone using this project. This avoids typos, repetition and ensures a consistent usage of attribute values.
I would suggest creating a new file in `gomponents/html/attributevalues.go` where we can add exported constants.
Of course it might make more sense to expose these constants in a different package. Also, take these constant names with a pinch of salt, we should strive to have some obvious and consistent naming.

What do you think of this idea @markuswustenberg ? I think is really worth doing.

For example (pseudocode):

```go
Source(
    Type("image/webp"),
)
Form(
    AutoComplete("off"),
)
Input(
    Type("text"),
)
Input(
    Type("email"),
)
```

could be turned into:

```go
Source(
    Type(ImageWEBP),
)
Form(
    AutoComplete(Off),
)
Input(
    Type(InputTypeText),
)
Input(
    Type(InputTypeEmail),
)
```

**Comment by averageflow** [comment]
I would be happy to do some research and gather as many attribute values as possible and make a PR with them, but of course I would like some opinion on if you think this is worth it.

**Comment by markuswustenberg** [comment]
@averageflow thank you for the idea. I've actually tried something similar, but ended up deleting most of it again (for example, `InputHidden` for an `input` element with type `hidden` and a value given as a parameter, which is actually still there in the `components` package I see now). In practice, I never used the helpers, because the pain of writing out `Input(Type("hidden"), Value(""))` isn't large enough, I guess. With bigger components, it's a different story entirely.

I think it's also really hard to decide which components should be included and which not. With all the combinations, the API surface area could really quickly explode, and I think that would be confusing for most users.

As you might have guessed, I lean towards not including something like this in the gomponents core library. Maybe it would be worth it for you to create a small library on your own that uses gomponents, and get some real world testing of the idea, and then we can have a review round and see how it works out? I'd be happy to include it on the website at https://www.gomponents.com/mentions/

Thoughts?

**Comment by averageflow** [comment]
@markuswustenberg I fully understand your reasoning. I will start on it when I have some time left and make it a sort of useful extension to gomponents. The separation of concerns is definitely something good 👍🏼 I will keep you posted

**Comment by markuswustenberg** [comment]
@averageflow nice, sounds good. 😊 I'll keep this issue open for updates.

**Comment by averageflow** [comment]
Began working on this https://github.com/averageflow/htmlgonstants. I expect it will take some time to get a more finished and useful project.

**Comment by markuswustenberg** [comment]
> Began working on this https://github.com/averageflow/htmlgonstants. I expect it will take some time to get a more finished and useful project.

Cool! Love the name. :D I'll follow it and see where it's heading.

**Comment by markuswustenberg** [comment]
@averageflow how's your experience with the constants? Does it make creating views easier for you?

I've thought about it a bit since. I really like the idea that it guards against typos in strings, but I'm a bit worried about increasing the API surface area by a lot, because there are so many possible values. Do you have any thoughts about that?
